name = "akitsu-cms"
main = "src/runtime/api.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat_v2"]

[env.development]
name = "akitsu-cms-dev"

[env.production]
name = "akitsu-cms-prod"

[[d1_databases]]
binding = "DB"
database_name = "cms-db"
database_id = "6ebc2e92-9be4-4238-9ddc-749afa09142e"

[vars]
ENVIRONMENT = "development"
